# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b0055530e7b830f3c98c80491e25ca5acaa74839043afefe5ac1aedce1722f94dec5cd8f3990f68124995f547c4023b09e64efc2a52763ca7c73f3f6b92c259

test:
  secret_key_base: ca03bac1764be5d2c6e3de10db5d6743700431c5c1ed5352bfbb4a7dae3fe803bd62f5d5d0b0aae42b7ecbe7e3e4de99af44881e6ffb6d31966855ff6fdc09f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
